spring:
  application:
    name: MyBatisPlus

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_PASSWORD:xiaobai}
    url: jdbc:mysql://127.0.0.1:3306/mybatis-plus

mybatis-plus:
  type-aliases-package: com.xiaobai.mybatisplus.entity # ?????
  mapper-locations: classpath*:/mapper/**/*.xml  # Mapper.xml ????
  configuration:
    map-underscore-to-camel-case: true # ????????????
    cache-enabled: false  # ????????
  global-config:
    db-config:
      id-type: assign_id # id???????
      update-strategy: not_null # ????????????

logging:
  level:
    com.xiaobai.mybatisplus.mapper: debug

